apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |-
    # TODO: Remove Copilot when it is supported on LiteLLM
    model_list:
      # Gemini 2.5 Pro 05-06
      - model_name: gemini-2.5-pro
        litellm_params:
          model: openai/gemini-2.5-pro-preview-05-06
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
          rpm: 7
        model_info:
          id: voidai-gemini-2.5-pro

      - model_name: gemini-gemini-2.5-pro
        litellm_params:
          model: gemini/gemini-2.5-pro-preview-05-06
        model_info:
          id: gemini-gemini-2.5-pro

      - model_name: copilot-gemini-2.5-pro
        litellm_params:
          model: openai/gemini-2.5-pro
          api_base: http://copilot-api.open-webui.svc.cluster.local:4141
          api_key: blabladoesntmatter
        model_info:
          id: copilot-gemini-2.5-pro

      # O3-high
      - model_name: o3-high
        litellm_params:
          model: openai/o3-high
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
          rpm: 7
        model_info:
          id: voidai-o3-high

      # O3-medium
      - model_name: o3-medium
        litellm_params:
          model: openai/o3-medium
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
          rpm: 7
        model_info:
          id: voidai-o3-medium

      # Claude Sonnet 4
      - model_name: claude-sonnet-4
        litellm_params:
          model: openai/claude-sonnet-4
          api_base: http://copilot-api.open-webui.svc.cluster.local:4141
          api_key: blabladoesntmatter
        model_info:
          id: copilot-claude-sonnet-4

      # GPT-4o
      - model_name: gpt-4o
        litellm_params:
          model: openai/gpt-4o
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
          rpm: 7
        model_info:
          id: voidai-gpt-4o
      - model_name: copilot-gpt-4o
        litellm_params:
          model: openai/gpt-4o
          api_base: http://copilot-api.open-webui.svc.cluster.local:4141
          api_key: blabladoesntmatter
        model_info:
          id: copilot-gpt-4o

      # o4-mini
      - model_name: o4-mini
        litellm_params:
          model: openai/o4-mini
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
          rpm: 7
        model_info:
          id: voidai-o4-mini

      - model_name: copilot-o4-mini
        litellm_params:
          model: openai/o4-mini
          api_base: http://copilot-api.open-webui.svc.cluster.local:4141
          api_key: blabladoesntmatter
        model_info:
          id: copilot-o4-mini

      # gpt-4.1
      - model_name: gpt-4.1
        litellm_params:
          model: openai/gpt-4.1
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
          rpm: 7
        model_info:
          id: voidai-gpt-4.1

      - model_name: copilot-gpt-4.1
        litellm_params:
          model: openai/gpt-4.1
          api_base: http://copilot-api.open-webui.svc.cluster.local:4141
          api_key: blabladoesntmatter
        model_info:
          id: copilot-gpt-4.1

      # gpt-image-1
      - model_name: gpt-image-1
        litellm_params:
          model: openai/gpt-image-1
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
          rpm: 7
        model_info:
          id: voidai-gpt-image-1

    litellm_settings:
      num_retries: 3
      allowed_fails: 3
      cooldown_time: 30
      drop_params: True
      cache: true
      cache_params:
        type: redis
        host: dragonfly-litellm
      fallbacks:
        - gemini-2.5-pro:
          - gemini-gemini-2.5-pro
          - copilot-gemini-2.5-pro
        - o4-mini:
          - copilot-o4-mini
        - gpt-4.1:
          - copilot-gpt-4.1
        - gpt-4o:
          - copilot-gpt-4o

    general_settings:
      alerting: ["slack"]
      alert_types:
        - "llm_exceptions"
        - "llm_too_slow"
        - "llm_requests_hanging"
        - "db_exceptions"
        - "daily_reports"
        - "new_model_added"
        - "outage_alerts"
