apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |-
    # TODO: Remove Copilot when it is supported on LiteLLM
    model_list:
      # Gemini 2.5 Pro 05-06
      - model_name: gemini-2.5-pro
        litellm_params:
          model: gemini/gemini-2.5-pro-preview-05-06
        model_info:
          id: gemini-2.5-pro-preview-05-06

      - model_name: copilot-gemini-2.5-pro
        litellm_params:
          model: openai/gemini-2.5-pro
          api_base: http://copilot-api:4141
          api_key: blabladoesntmatter
        model_info:
          id: gemini-2.5-pro-preview-05-06
      
      # GPT-5
      - model_name: gpt-5
        litellm_params:
          model: openai/gpt-5
          api_base: http://copilot-api:4141
          api_key: blabladoesntmatter
        model_info:
          id: gpt-5

      # O3-high
      - model_name: o3-high
        litellm_params:
          model: openai/o3
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
          reasoning_effort: "high"
        model_info:
          id: o3
      # O3-medium
      - model_name: o3-medium
        litellm_params:
          model: openai/o3
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
          reasoning_effort: "medium"
        model_info:
          id: o3


      # Claude Sonnet 4
      - model_name: claude-sonnet-4
        litellm_params:
          model: openai/claude-sonnet-4
          api_base: http://copilot-api:4141
          api_key: blabladoesntmatter
        model_info:
          id: claude-sonnet-4

      # GPT-4o
      - model_name: gpt-4o
        litellm_params:
          model: openai/gpt-4o
          api_base: http://copilot-api:4141
          api_key: blabladoesntmatter
        model_info:
          id: gpt-4o


      - model_name: o4-mini
        litellm_params:
          model: openai/o4-mini
          api_base: http://copilot-api:4141
          api_key: blabladoesntmatter
        model_info:
          id: o4-mini

      # gpt-4.1
      - model_name: gpt-4.1
        litellm_params:
          model: openai/gpt-4.1
          api_base: http://copilot-api:4141
          api_key: blabladoesntmatter
        model_info:
          id: gpt-4.1

      # gpt-oss-120b
      - model_name: gpt-oss-120b
        litellm_params:
          model: openai/openai/gpt-oss-120b
          api_base: https://llm.chutes.ai/v1
          api_key: "os.environ/CHUTES_API_KEY"
        model_info:
          id: gpt-oss-120b

      # text-embedding-3-large
      - model_name: text-embedding-3-large
        litellm_params:
          model: openai/text-embedding-3-large
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
        model_info:
          id: text-embedding-3-large

      # text-embedding-3-small
      - model_name: text-embedding-3-small
        litellm_params:
          model: openai/text-embedding-3-small
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"
        model_info:
          id: text-embedding-3-small


      # qwen3-coder
      - model_name: qwen3-coder
        litellm_params:
          model: openai/Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8
          api_base: https://llm.chutes.ai/v1
          api_key: "os.environ/CHUTES_API_KEY"
        model_info:
          id: qwen3-coder

      - model_name: qwen3-coder
        litellm_params:
          model: openrouter/qwen/qwen3-coder:free
          api_key: "os.environ/OPENROUTER_API_KEY"

      # kimi-k2-instruct
      - model_name: kimi-k2-instruct
        litellm_params:
          model: openai/moonshotai/Kimi-K2-Instruct
          api_base: https://llm.chutes.ai/v1
          api_key: "os.environ/CHUTES_API_KEY"
        model_info:
          id: kimi-k2-instruct

      - model_name: kimi-k2-instruct
        litellm_params:
          model: openrouter/moonshotai/kimi-k2:free
          api_key: "os.environ/OPENROUTER_API_KEY"

      # gpt-image-1
      - model_name: gpt-image-1
        litellm_params:
          model: openai/gpt-image-1
          api_base: https://api.voidai.app/v1
          api_key: "os.environ/VOIDAI_API_KEY"

    litellm_settings:
      num_retries: 3
      allowed_fails: 3
      cooldown_time: 30
      drop_params: True
      cache: false
      fallbacks:
        - gemini-2.5-pro:
          - copilot-gemini-2.5-pro
    general_settings:
      alerting: ["slack"]
      alert_types:
        - "llm_exceptions"
        - "llm_too_slow"
        - "llm_requests_hanging"
        - "db_exceptions"
        - "daily_reports"
        - "new_model_added"
        - "outage_alerts"
