apiVersion: v1
kind: ConfigMap
metadata:
  name: moniquet-config
data:
  config.yaml: |-
    interval: 3
    log_level: info
    longhorn:
      enabled: true
      namespace: "longhorn-system"
      alert_thresholds:
        volume_usage_percent: 90
        volume_capacity_critical: 2147483648
        replica_failure_count: 1
    node_monitoring:
      enabled: true
      cpu_threshold_percent: 80
