helmCharts:
  - name: gatus
    repo: https://twin.github.io/helm-charts
    version: 1.2.0
    releaseName: gatus
    namespace: gatus
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - ingressroute.yaml
