apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - data-persistentvolumeclaim.yaml
  - koito-deployment.yaml
  - koito-service.yaml
  - ingressroute.yaml
namespace: koito
secretGenerator:
  - name: production
    namespace: koito
    envs:
      - .env
    options:
      disableNameSuffixHash: true
images:
  - name: ghcr.io/kreatoo/koito-docker
    newTag: v0.0.12
