helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.18.0
    namespace: kube-system
    valuesFile: values.yaml
    apiVersions:
      - gateway.networking.k8s.io/v1/GatewayClass
