ipam:
  mode: kubernetes
ipv4:
  enabled: true
ipv6:
  enabled: true
kubeProxyReplacement: true
k8sServiceHost: localhost
k8sServicePort: 7445
bpf:
  masquerade: true
ipMasqAgent:
  enabled: true
  config:
    # Pods can't reach Tailscale IPs if we don't masquerade them
    # Which is why this whole section is here
    nonMasqueradeCIDRs:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
encryption:
  enabled: true
  type: wireguard
  nodeEncryption: true
hubble:
  relay:
    enabled: false
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

socketLB:
  hostNamespaceOnly: true

# Specify which device(s) run the eBPF datapath. Must be a string.
devices: "eth0,tailscale0"

gatewayAPI:
  enabled: false # Enable it after a Cilium release that fixes https://github.com/cilium/cilium/issues/38420 is released
