resources:
  - namespace.yaml
  - issuer.yaml
  - wildcard-cert.yaml
  - wildcard-cert-kreato.dev.yaml
  - gateway.yaml
sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
      - Namespace
      - customResourceDefinition
    orderLast:
      - ClusterIssuer
      - Certificate
generatorOptions:
  disableNameSuffixHash: true
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.18.2
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      installCRDs: true
secretGenerator:
  - name: cloudflare-api-token-secret
    namespace: cert-manager
    envs:
      - .env
