apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-krea.to
  namespace: traefik
spec:
  secretName: wildcard-krea.to-tls
  dnsNames:
    - "krea.to"
    - "*.krea.to"
    - "*.internal.krea.to"
  issuerRef:
    name: mainissuer
    kind: ClusterIssuer
