resources:
  - namespace.yaml
  - cloudflare-middleware.yaml
  - ratelimit-middleware.yaml
sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
      - Namespace
      - customResourceDefinition
    orderLast:
      - Middleware
      - TLSStore
namespace: traefik
helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 35.4.0
    releaseName: traefik
    valuesFile: values.yaml
    namespace: traefik
  - name: traefik-crds
    repo: https://traefik.github.io/charts
    version: 1.8.1
    releaseName: traefik-crds
    namespace: traefik
