apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-ssl-secrets
  namespace: traefik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ocis
  to:
    - group: ""
      kind: Secret
      name: wildcard-krea.to-tls
