apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-ssl-secrets-litellm
  namespace: traefik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: litellm
  to:
    - group: ""
      kind: Secret
      name: wildcard-krea.to-tls
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-ssl-secrets-ocis
  namespace: traefik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: ocis
  to:
    - group: ""
      kind: Secret
      name: wildcard-krea.to-tls
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-to-ssl-secrets-minio
  namespace: traefik
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: minio
  to:
    - group: ""
      kind: Secret
      name: wildcard-krea.to-tls
