updateStrategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

deployment:
  replicas: 2
gateway:
  enabled: true
  listeners:
    websecure:
      port: 8443
      protocol: HTTPS
      certificateRefs:
        - kind: Secret
          name: wildcard-krea.to-tls
          namespace: cert-manager
providers:
  kubernetesGateway:
    enabled: true
ports:
  websecure:
    hostPort: 443
    middlewares:
      - traefik-cloudflare@kubernetescrd
ingressClass:
  enabled: true
  isDefaultClass: true
additionalArguments:
  - --providers.kubernetescrd.allowCrossNamespace=true
  - --entrypoints.name.http3
tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-krea.to-tls
