deployment:
  replicas: 2
  revisionHistoryLimit: 0
ports:
  websecure:
    hostPort: 443
    middlewares:
      - traefik-cloudflare@kubernetescrd
ingressClass:
  enabled: true
  isDefaultClass: true
additionalArguments:
  - --providers.kubernetescrd.allowCrossNamespace=true
  - --entrypoints.name.http3
tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard-krea.to-tls
