apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis
  namespace: ocis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocis
  template:
    metadata:
      labels:
        app: ocis
    spec:
      containers:
        - name: ocis
          image: owncloud/ocis
          command: ["/bin/sh"]
          args: ["-c", "ocis init || true; ocis server"]
          envFrom:
            - configMapRef:
                name: env
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: ocis-data
              mountPath: /var/lib/ocis
            - name: ocis-config
              mountPath: /etc/ocis
      volumes:
        - name: ocis-data
          persistentVolumeClaim:
            claimName: ocis-data
        - name: ocis-config
          persistentVolumeClaim:
            claimName: ocis-config
      restartPolicy: Always
