apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ocis
  namespace: ocis
spec:
  parentRefs:
    - name: ocis-gateway
      sectionName: websecure

  hostnames:
    - "cloud.krea.to"

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /signin/
      backendRefs:
        - name: ocis
          port: 9200
          kind: Service
          namespace: ocis
          filters:
            - type: ExtensionRef
              extensionRef:
                group: traefik.io
                kind: Middleware
                name: ratelimit
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ocis
          port: 9200
          kind: Service
          namespace: ocis
