namespace: longhorn-system
resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.8.1/deploy/longhorn.yaml
patches:
  - path: namespace.yaml
#- networkpolicy.yaml
#  - ingressroute.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: s3-creds
    namespace: longhorn-system
    envs:
      - .env
