namespace: longhorn-system
resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.9.1/deploy/longhorn.yaml
patches:
  - path: namespace.yaml
  - path: control-plane-toleration.yaml
#- networkpolicy.yaml
#  - gateway.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: s3-creds
    namespace: longhorn-system
    envs:
      - .env
