resources:
  - namespace.yaml
sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
      - Namespace
      - customResourceDefinition
helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.26.0
    namespace: cnpg-system
    valuesInline:
      webhook:
        mutating:
          failurePolicy: Ignore
        validating:
          failurePolicy: Ignore
