apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9000 
    targetPort: 9000
    name: api
  - port: 9001 
    targetPort: 9001
    name: console
