resources:
  - namespace.yaml
  - networkpolicy.yaml
  - ingressroute.yaml

namespace: jellyfin

helmCharts:
  - name: jellyfin
    repo: https://jellyfin.github.io/jellyfin-helm
    version: 2.3.0
    releaseName: jellyfin
    valuesFile: values.yaml
    namespace: jellyfin
