name: Deploy
on:
  workflow_call:
permissions:
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:k8s-deploy
          version: latest
          hostname: kreat8s-deploy
      - name: Install kubectl
        uses: Azure/setup-kubectl@v4.0.1
      - name: Install Helm
        uses: Azure/setup-helm@v4.3.0
      - name: Add kubeconfig
        env:
          KUBECTLCONFFULL: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECTLCONFFULL" > $HOME/.kube/config
      - name: Add .env files
        env:
          CERTMANAGERENV: ${{ secrets.CERTMANAGERENV }}
          LITELLMENV: ${{ secrets.LITELLMENV }}
          LONGHORNENV: ${{ secrets.LONGHORNENV }}
          UMAMIENV: ${{ secrets.UMAMIENV }}
          SUNENV: ${{ secrets.SUNENV }}
          KOITOENV: ${{ secrets.KOITOENV }}
        run: |
          cd manifests
          echo "$CERTMANAGERENV" > core/cert-manager/.env
          echo "$SUNENV" > core/sun/.env
          echo "$LITELLMENV" > apps/litellm/.env
          echo "$UMAMIENV" > apps/umami/.env
          echo "$LONGHORNENV" > core/longhorn/.env
          echo "$KOITOENV" > apps/koito/.env
      - name: Add hack for immutable jobs
        run: |
          kubectl delete -n traefik job cert-manager-startupapicheck || true
      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/bin --tag 1.40.0

      - name: Run Kustomize
        run: just --yes deploy-manifests
