name: Kubernetes Image Vulnerability Scan

on:
  schedule:
    - cron: '0 3 * * *' # Daily at 03:00 UTC
  workflow_dispatch:
    {}

permissions:
  contents: read
  security-events: write

jobs:
  trivy-k8s-scan:
    name: Scan running Kubernetes images (JSON)
    runs-on: ubuntu-latest
    steps:
      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:k8s-deploy
          hostname: kreat8s-scan
          use-cache: true

      - name: Install kubectl
        uses: Azure/setup-kubectl@v4.0.1

      - name: Configure kubeconfig from secret
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p "$HOME/.kube"
          echo "$KUBECONFIG" > "$HOME/.kube/config"
          chmod 600 "$HOME/.kube/config"

      - name: Verify cluster access
        run: |
          kubectl version
          kubectl get nodes

      - name: Install Trivy
        shell: bash
        run: |
          set -euo pipefail
          echo "Installing Trivy via official install script..."
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
          trivy --version

      - name: Scan Kubernetes for image vulnerabilities (CRITICAL,HIGH)
        shell: bash
        run: |
          set -euo pipefail
          echo 'Updating Trivy DB (this may take a moment)...'
          trivy --download-db-only || true

          echo 'Scanning entire cluster...'
          trivy k8s \
            --format json \
            --report summary \
            --output trivy-k8s.json \
            --severity CRITICAL,HIGH \
            --ignore-unfixed \
            --scanners vuln \
            --disable-node-collector \
            --timeout 15m

          echo 'Scan complete; JSON saved to trivy-k8s.json'

      - name: Upload Trivy JSON report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-k8s-json
          path: trivy-k8s.json

      - name: Convert Trivy JSON to SARIF
        shell: bash
        run: |
          set -euo pipefail
          trivy convert --format sarif -o trivy-k8s.sarif trivy-k8s.json

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-k8s.sarif
          category: k8s-image-scan
