name: Complete Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    uses: ./.github/workflows/yaml-lint.yml

  validate-k8s:
    needs: format
    uses: ./.github/workflows/k8s-static-val.yaml

  validate-tofu:
    needs: format
    uses: ./.github/workflows/tofu.yml

  check-deployment:
    needs: validate-k8s
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      should_deploy: ${{ steps.should-deploy.outputs.should_deploy }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            vars.yaml
          files_yaml: |
            tofu:
              - 'tofu/**'
      
      - name: Check if deployment should run
        id: should-deploy
        run: |
          if [[ "${{ steps.changed-files.outputs.vars_any_changed }}" == "true" ]]; then
            if [[ "${{ steps.changed-files.outputs.tofu_any_changed }}" == "true" ]]; then
              echo "should_deploy=true" >> $GITHUB_OUTPUT
              echo "Deploying because vars.yaml and tofu/ files were both modified"
            else
              echo "should_deploy=false" >> $GITHUB_OUTPUT
              echo "Skipping deployment because only vars.yaml was modified"
            fi
          else
            echo "should_deploy=true" >> $GITHUB_OUTPUT
            echo "Deploying because vars.yaml was not modified"
          fi

  deploy-k8s:
    needs: check-deployment
    uses: ./.github/workflows/deploy-k8s.yml
    secrets: inherit
    if: needs.check-deployment.outputs.should_deploy == 'true'
