name: Complete Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    uses: ./.github/workflows/yaml-lint.yml
    
  validate-k8s:
    needs: format
    uses: ./.github/workflows/k8s-static-val.yaml

  validate-tofu:
    needs: format
    uses: ./.github/workflows/tofu.yml 
