name: Complete Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    uses: ./.github/workflows/yaml-lint.yml

  validate-k8s:
    needs: format
    uses: ./.github/workflows/k8s-static-val.yaml

  validate-tofu:
    needs: format
    uses: ./.github/workflows/tofu.yml

  deploy-k8s:
    needs: validate-k8s
    uses: ./.github/workflows/deploy-k8s.yml
    secrets: inherit
    if: github.ref == 'refs/heads/main' && (!contains(github.event.head_commit.modified, 'vars.yaml') || contains(github.event.head_commit.modified, 'vars.yaml') && contains(github.event.head_commit.modified, 'tofu/'))
