name: Run Water

permissions:
  contents: read
  id-token: write

on:
  push:
    paths:
      - 'water.yaml'
      - 'water.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  water:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Connect Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:k8s-deploy
          hostname: bouquet2-talos-update
          use-cache: true

      - name: Add talosconfig
        env:
          TALOSCONFIG: ${{ secrets.TALOSCONFIG }}
        run: |
          mkdir -p ~/.talos
          echo "$TALOSCONFIG" > ~/.talos/config
          chmod 600 ~/.talos/config

      - name: Add kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBECONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Download water
        run: |
          LATEST_WATER_VERSION=$(curl -s https://api.github.com/repos/bouquet2/water/releases/latest | jq -r '.tag_name' | sed 's/v//')
          curl https://github.com/bouquet2/water/releases/download/v${LATEST_WATER_VERSION}/water_${LATEST_WATER_VERSION}_linux_amd64.tar.gz -L -o water.tar.gz
          tar -xzf water.tar.gz
          chmod +x water
          ./water --version

      - name: Run water
        run: |
          ./water
