apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: maloja
  name: maloja
spec:
  replicas: 2
  selector:
    matchLabels:
      service: maloja
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: maloja
    spec:
      containers:
        - image: krateng/maloja
          name: maloja
          env:
            - name: MALOJA_DATA_DIRECTORY
              value: /data
            - name: PGID
              value: "0"
            - name: PUID
              value: "0"
          ports:
            - containerPort: 42010
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
